# configures the Android and iOS version. Needs to parse as a Java properties file as well as a bash script (we source it to parse it).
VERSION_MAJOR=7
VERSION_MINOR=1
VERSION_PATCH=0
VERSION_TYPE=

IOS_APPLOVIN_ADAPTER_VERSION=1.0.0
IOS_FIREBASE_ADAPTER_VERSION=1.0.0
IOS_IRONSOURCE_ADAPTER_VERSION=1.0.0
IOS_UNITYADS_ADAPTER_VERSION=1.0.0