# configures the Android and iOS version. Needs to parse as a Java properties file as well as a bash script (we source it to parse it).
VERSION_MAJOR=8
VERSION_MINOR=0
VERSION_PATCH=0
VERSION_TYPE=

IOS_APPLOVIN_ADAPTER_VERSION=1.0.2
IOS_FIREBASE_ADAPTER_VERSION=1.0.0
IOS_IRONSOURCE_ADAPTER_VERSION=2.0.0
IOS_UNITYADS_ADAPTER_VERSION=1.0.1
IOS_GOOGLEODM_ADAPTER_VERSION=1.0.1
