import AdServices
import AppTrackingTransparency
import StoreKit

#if DEBUG
	import Darwin
#endif

public protocol JustTrackSdk: AnyObject {
	/// This future eventually resolves to the latest attribution response for the user. If the attribution of a user changes,
	/// a different future with the updated attribution will be provided.
	var attribution: Future<AttributionResponse> { get }

	/// Resolves to the retargeting parameters from the attribution response (if the user was attributed to a retargeting campaign).
	var retargetingParameters: Future<RetargetingParameters?> { get }

	/// Contains the preliminary retargeting parameters (should we already know that the user will most likely get
	/// attributed to a retargeting campaign, but this wasn't validated with the justtrack backend yet).
	var preliminaryRetargetingParameters: PreliminaryRetargetingParameters? { get }

	/// Returns the version of the app at the time the app was installed.
	var appVersionAtInstall: AppVersion { get }

	/// Contains the current version of the justtrack SDK used by your app.
	var sdkVersion: any Version { get }

	/// Remote config functionality for retrieving and activating experiment assignments.
	var remoteConfig: JusttrackRemoteConfig { get }

	/// Anonymize a user's installs, events, and sessions.
	///
	/// Instruct the justtrack backend to delete identifying information about the user.
	/// - Returns: A future which resolves as soon as the backend was notified.
	func anonymize() -> Future<Void>

	/// Returns `true` if the SDK instance is running, otherwise returns `false`.
	func isRunning() -> Bool

	/// Register a listener to get notified about changes to the attribution of a user (an attribution can change
	/// shortly after the app install or when the user returns to the app via a retargeting campaign).
	func register(attributionListener: @escaping (AttributionResponse) -> Void) -> Subscription

	/// Register a listener to get notified about changes to the retargeting parameters.
	func register(retargetingParametersListener: @escaping (RetargetingParameters) -> Void) -> Subscription

	/// Register a listener to get notified about changes to the preliminary retargeting parameters.
	func register(preliminaryRetargetingParametersListener: @escaping (PreliminaryRetargetingParameters) -> Void) -> Subscription

	/// Shutdown the justtrack SDK and stop all running processes of the SDK. You mustn't call any methods on the SDK after shutting it down.
	func shutdown()

	/// Set a user id from your own backend and forward it to the justtrack backend. This allows you to provide server-side
	/// events while using your own identifier for a user. Returns a future which resolves as soon as your user ID has reached
	/// the justtrack backend.
	///
	/// This method already handles deduplicating requests, thus calling this method (also over different executions of
	/// your app) is idempotent.
	func set(userId: String) -> Future<Void>

	/// Set the Firebase App Instance ID for the current user. This is only needed if you don't use the automatic integration
	/// with Firebase. Forwards the App Instance ID to the justtrack backend, making it available for sending postbacks to
	/// Firebase from backend side.
	///
	/// This method contains the same deduplication and retry logic like set(customUserId:).
	func set(firebaseAppInstanceId: String) -> Future<Void>

	/// Set the ODM (On Device Measurement) info from Google Ads.
	/// This triggers a re-attribution with the ODM info included.
	func set(odmInfo: String) -> Future<Void>

	/// Handle an incoming deeplink URL.
	///
	/// Call this method when your app receives a deeplink URL (e.g. in `application(_:open:options:)`,
	/// `application(_:continue:restorationHandler:)`, or SwiftUI's `.onOpenURL`).
	/// The SDK will extract the `gbraid` parameter from the URL's query parameters (if present) and
	/// include it in the next attribution request to the justtrack backend.
	///
	/// - Parameter url: The deeplink URL received by your app.
	func handle(deeplink url: URL)

	/// Configure automatic in-app purchase forwarding to the justtrack backend for the execution of the app. By default,
	/// the justtrack SDK forwards in-app purchases to the justtrack backend to track the revenue generated by a user.
	/// You can use this method to opt out of this behavior.
	func set(automaticInAppPurchaseTracking: Bool)

	/// Starts the SDK.
	///
	/// The SDK starts tracking the user only after the start method is called. User's unique IDs, install and app events will only be tracked after the method is used. Any event preceding the start call will not be reported by the SDK.
	func start()

	/// After this API is called, the SDK will no longer send any data to the justtrack servers.
	///
	/// The SDK stops tracking the user entirely. No ID's or app events will be tracked or reported. Any app events collected before the stop method is called will still be reported.
	func stop()

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@available(*, deprecated, renamed: "track")
	@discardableResult
	func publish(event: AppEvent) -> Future<Void>

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(event: AppEvent) -> Future<Void>

	/// Forward an ad impression and count the revenue generated from the impression for your app (if you provided a revenue value).
	/// - Returns: A future which resolves as soon as the backend was notified.
	@discardableResult
	func forward(adImpression: AdImpression) -> Future<Void>

	/// Returns the unique id of the current install of the user.
	func getInstallInstanceId() -> Future<String>

	/// Returns the used advertiser ID (IDFA) and whether the user limited ad tracking.
	func getAdvertiserIdInfo() -> Future<AdvertiserIdInfo>

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - tags: You can add tags to your experiments which can describe the purpose of it later filter through them. The array shouldn't contain more than 5 elements. Each tag must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - happenedAt: The time at which the user was assigned to the test group. Defaults to the time at which the server received the assignment request if not provided.
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String, tags: [String], happenedAt: Date?) -> Future<Void>

	/// Forwards StoreKit 2 transactions for in-app purchases and subscriptions from your app to the justtrack backend.
	@available(iOS 15.0, *)
	@discardableResult
	func forward(transaction: Transaction) -> Result<Void, Error>

	/// Forwards StoreKit 2 transaction id, product id, and quantity for in-app purchases and subscriptions from your app to the justtrack backend.
	@available(iOS 15.0, *)
	@discardableResult
	func forward(transactionId: String, productId: String, quantity: Int) -> Result<Void, Error>

	/// Integrates a custom adapter with the justtrack SDK.
	///
	/// Use this method to link third-party or custom adapters that conform to `JustTrackSDKAdapter` with the SDK. The adapter will be initialized and integrated, allowing it to forward events or data to the SDK as needed.
	/// - Parameter adapter: The adapter instance conforming to `JusttrackAdapter`.
	/// - Returns: A future which resolves once the adapter integration is complete or fails if an error occurs.
	@discardableResult
	func integrate(with adapter: JusttrackAdapter) -> Future<Void>

	/// Sets the value for global dimension 0 (`jt_global_0`).
	///
	/// Global dimensions are automatically attached to all future events sent by the SDK.
	/// They persist across sessions and app launches until explicitly cleared or the app is re-installed.
	/// - Parameter value: The dimension value. Pass `nil` to clear the dimension.
	func set(globalDimension0 value: String?)

	/// Sets the value for global dimension 1 (`jt_global_1`).
	///
	/// Global dimensions are automatically attached to all future events sent by the SDK.
	/// They persist across sessions and app launches until explicitly cleared or the app is re-installed.
	/// - Parameter value: The dimension value. Pass `nil` to clear the dimension.
	func set(globalDimension1 value: String?)

	/// Sets the value for global dimension 2 (`jt_global_2`).
	///
	/// Global dimensions are automatically attached to all future events sent by the SDK.
	/// They persist across sessions and app launches until explicitly cleared or the app is re-installed.
	/// - Parameter value: The dimension value. Pass `nil` to clear the dimension.
	func set(globalDimension2 value: String?)
}

public extension JustTrackSdk {

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(eventName: String) -> Future<Void> {
		track(event: AppEvent(eventName))
	}

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(eventName: String, dimensions: Dimensions) -> Future<Void> {
		track(event: AppEvent(name: eventName, dimensions: dimensions))
	}

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// This convenience method calls `setExperimentVariant` with `tags` and `happenedAt` set to nil.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String) -> Future<Void> {
		setExperimentVariant(experiment: experiment, variant: variant, tags: [], happenedAt: nil)
	}

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// This convenience method calls `setExperimentVariant` with `happenedAt` set to nil.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - tags: You can add tags to your experiments which can describe the purpose of it later filter through them. The array shouldn't contain more than 5 elements. Each tag must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String, tags: [String]) -> Future<Void> {
		setExperimentVariant(experiment: experiment, variant: variant, tags: tags, happenedAt: nil)
	}
}
