import AdServices
import AppTrackingTransparency
import StoreKit

#if DEBUG
	import Darwin
#endif

public protocol JustTrackSdk: AnyObject {
	/// The test group of a user is an integer from the set [1, 2, 3]. It might be nil on non-standard devices.
	@available(*, deprecated)
	var testGroupId: Int? { get }

	/// This future eventually resolves to the latest attribution response for the user. If the attribution of a user changes,
	/// a different future with the updated attribution will be provided.
	var attribution: Future<AttributionResponse> { get }

	/// Resolves to the retargeting parameters from the attribution response (if the user was attributed to a retargeting campaign).
	var retargetingParameters: Future<RetargetingParameters?> { get }

	/// Contains the preliminary retargeting parameters (should we already know that the user will most likely get
	/// attributed to a retargeting campaign, but this wasn't validated with the justtrack backend yet).
	var preliminaryRetargetingParameters: PreliminaryRetargetingParameters? { get }

	/// Returns the version of the app at the time the app was installed.
	var appVersionAtInstall: AppVersion { get }

	/// Contains the current version of the justtrack SDK used by your app.
	var sdkVersion: any Version { get }

	/// Remote config functionality for retrieving and activating experiment assignments.
	var remoteConfig: JusttrackRemoteConfig { get }

	/// Anonymize a user's installs, events, and sessions.
	///
	/// Instruct the justtrack backend to delete identifying information about the user.
	/// - Returns: A future which resolves as soon as the backend was notified.
	func anonymize() -> Future<Void>

	/// Returns `true` if the SDK instance is running, otherwise returns `false`.
	func isRunning() -> Bool

	/// Register a listener to get notified about changes to the attribution of a user (an attribution can change
	/// shortly after the app install or when the user returns to the app via a retargeting campaign).
	func register(attributionListener: @escaping (AttributionResponse) -> Void) -> Subscription

	/// Register a listener to get notified about changes to the retargeting parameters.
	func register(retargetingParametersListener: @escaping (RetargetingParameters) -> Void) -> Subscription

	/// Register a listener to get notified about changes to the preliminary retargeting parameters.
	func register(preliminaryRetargetingParametersListener: @escaping (PreliminaryRetargetingParameters) -> Void) -> Subscription

	/// Shutdown the justtrack SDK and stop all running processes of the SDK. You mustn't call any methods on the SDK after shutting it down.
	func shutdown()

	/// Set a user id from your own backend and forward it to the justtrack backend. This allows you to provide server-side
	/// events while using your own identifier for a user. Returns a future which resolves as soon as your user ID has reached
	/// the justtrack backend.
	///
	/// This method already handles deduplicating requests, thus calling this method (also over different executions of
	/// your app) is idempotent.
	func set(userId: String) -> Future<Void>

	/// Set the Firebase App Instance ID for the current user. This is only needed if you don't use the automatic integration
	/// with Firebase. Forwards the App Instance ID to the justtrack backend, making it available for sending postbacks to
	/// Firebase from backend side.
	///
	/// This method contains the same deduplication and retry logic like set(customUserId:).
	func set(firebaseAppInstanceId: String) -> Future<Void>

	/// Set the ODM (On Device Measurement) info from Google Ads.
	/// This triggers a re-attribution with the ODM info included.
	func set(odmInfo: String) -> Future<Void>

	/// Configure automatic in-app purchase forwarding to the justtrack backend for the execution of the app. By default,
	/// the justtrack SDK forwards in-app purchases to the justtrack backend to track the revenue generated by a user.
	/// You can use this method to opt out of this behavior.
	func set(automaticInAppPurchaseTracking: Bool)

	/// Starts the SDK.
	///
	/// The SDK starts tracking the user only after the start method is called. User's unique IDs, install and app events will only be tracked after the method is used. Any event preceding the start call will not be reported by the SDK.
	func start()

	/// After this API is called, the SDK will no longer send any data to the justtrack servers.
	///
	/// The SDK stops tracking the user entirely. No ID's or app events will be tracked or reported. Any app events collected before the stop method is called will still be reported.
	func stop()

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@available(*, deprecated, renamed: "track")
	@discardableResult
	func publish(event: AppEvent) -> Future<Void>

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(event: AppEvent) -> Future<Void>

	/// Forward an ad impression and count the revenue generated from the impression for your app (if you provided a revenue value).
	/// - Returns: A future which resolves as soon as the backend was notified.
	@discardableResult
	func forward(adImpression: AdImpression) -> Future<Void>

	/// Returns the unique id of the current install of the user.
	func getInstallInstanceId() -> Future<String>

	/// Returns the used advertiser ID (IDFA) and whether the user limited ad tracking.
	func getAdvertiserIdInfo() -> Future<AdvertiserIdInfo>

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - tags: You can add tags to your experiments which can describe the purpose of it later filter through them. The array shouldn't contain more than 5 elements. Each tag must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - happenedAt: The time at which the user was assigned to the test group. Defaults to the time at which the server received the assignment request if not provided.
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String, tags: [String], happenedAt: Date?) -> Future<Void>

	/// Forwards StoreKit 2 transactions for in-app purchases and subscriptions from your app to the justtrack backend.
	@available(iOS 15.0, *)
	@discardableResult
	func forward(transaction: Transaction) -> Result<Void, Error>

	/// Forwards StoreKit 2 transaction id, product id, and quantity for in-app purchases and subscriptions from your app to the justtrack backend.
	@available(iOS 15.0, *)
	@discardableResult
	func forward(transactionId: String, productId: String, quantity: Int) -> Result<Void, Error>

	/// Integrates a custom adapter with the justtrack SDK.
	///
	/// Use this method to link third-party or custom adapters that conform to `JustTrackSDKAdapter` with the SDK. The adapter will be initialized and integrated, allowing it to forward events or data to the SDK as needed.
	/// - Parameter adapter: The adapter instance conforming to `JusttrackAdapter`.
	/// - Returns: A future which resolves once the adapter integration is complete or fails if an error occurs.
	@discardableResult
	func integrate(with adapter: JusttrackAdapter) -> Future<Void>
}

public extension JustTrackSdk {

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(eventName: String) -> Future<Void> {
		track(event: AppEvent(eventName))
	}

	/// Track an event from your user (like performing some task, clicking some button, reaching some goal, ...) and
	/// send it to the justtrack backend. User events allow you to track users through the funnel of your app and can
	/// be analyzed on the justtrack dashboard.
	///
	/// The returned future resolves once the event has been sent to the server. If network conditions don't allow sending
	/// the event right now it will be sent to the backend later once connectivity improves.
	@discardableResult
	func track(eventName: String, dimensions: Dimensions) -> Future<Void> {
		track(event: AppEvent(name: eventName, dimensions: dimensions))
	}

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// This convenience method calls `setExperimentVariant` with `tags` and `happenedAt` set to nil.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String) -> Future<Void> {
		setExperimentVariant(experiment: experiment, variant: variant, tags: [], happenedAt: nil)
	}

	/// Use this method to share the information about the test group assigned to the user.
	///
	/// This convenience method calls `setExperimentVariant` with `happenedAt` set to nil.
	///
	/// - Parameters:
	///   - experiment: The name of the A/B test. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - variant: The test group the user is assigned to. Must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	///   - tags: You can add tags to your experiments which can describe the purpose of it later filter through them. The array shouldn't contain more than 5 elements. Each tag must be shorter than 255 characters and consist only of printable ASCII characters (U+0020 to U+007E).
	/// - Returns: A Future which resolves as soon as the backend was notified about the experiment variant.
	func setExperimentVariant(experiment: String, variant: String, tags: [String]) -> Future<Void> {
		setExperimentVariant(experiment: experiment, variant: variant, tags: tags, happenedAt: nil)
	}
}

final class JustTrackSdkImpl: JustTrackSdk, AppDelegateWatcherReportee, AdIdsProvider, EventPublisher, AdTrackingEventPublisherObserver {

	private static let attributionDurationMetric = Metric(metric: "AttributionDuration", unit: .seconds)

	var testGroupId: Int? {
		testGroupIdValue
	}

	var attribution: Future<AttributionResponse> {
		TransformingFuture(getAttributionOutput(forcedDecision: nil), { $0.attributionResponse }).toFuture()
	}

	var completeAttribution: Future<CompleteAttributionResponse> {
		TransformingFuture(getAttributionOutput(forcedDecision: nil), { $0.completeAttributionResponse }).toFuture()
	}

	var retargetingParameters: Future<RetargetingParameters?> {
		TransformingFuture(getAttributionOutput(forcedDecision: nil), { $0.retargetingParameters }).toFuture()
	}

	var preliminaryRetargetingParameters: PreliminaryRetargetingParameters? {
		preliminaryRetargetingParametersImpl
	}

	let appVersionAtInstall: AppVersion

	var sdkVersion: any Version {
		currentSdkVersion()
	}

	let remoteConfig: JusttrackRemoteConfig

	private let logger: HttpLogger
	private let bundleId: String
	private let platformType: PlatformType
	private let applicationVersion: AppVersion
	private var installId: StringID
	private let adTrackingProvider: AdTrackingProvider
	private var trackingId: String?
	private var trackingProvider: String?
	private var attributionOutput: Future<AttributionOutput>?
	private var testGroupIdValue: Int?
	private var attributionCanRetryAt: Date?
	private var preliminaryRetargetingParametersImpl: PreliminaryRetargetingParametersImpl?
	private let appVersionUpdateInfo: AppVersionUpdateInfo
	private var firebaseAppInstanceId: String?
	private var odmInfo: String?
	private let httpClient: HttpClient
	private let periodicLogsPublisher: PeriodicLogsPublisher
	private let claimsProvider: ClaimsProvider
	private let store: Store
	private weak var adIdsProviderWrapper: AdIdsProviderWrapper?
	private var adTrackingEventPublisher: AdTrackingEventPublishing?
	private var sessionManager: SessionManager?
	private var userEventQueue: PublishEventsQueue?
	// last install id of a successful (!) attribution. don't just read the install id from the store if it isn't a full attribution
	private var lastInstallId: StringID?
	private let attributionSubscriptions: SubscriptionManager<AttributionResponse>
	private let retargetingParamsSubscriptions: SubscriptionManager<RetargetingParameters>
	private let preliminaryRetargetingParamsSubscriptions: SubscriptionManager<PreliminaryRetargetingParameters>
	private let reAttributionDecider: ReAttributionDecider
	private let reFetchReAttributionDelay: TimeInterval
	private let attributionRetryDelay: TimeInterval
	private var connectivityManager: ConnectivityManager?
	private let delegateWatcher: AppDelegateWatcher
	private var purchaseTracker: InAppPurchaseTracker
	private var getAdIdsResult: FutureImpl<AdIds>
	private var needsToGetIdfa = true
	private let crashReporter: CrashReporter
	private let anrDetector: AnrDetector
	private let sqliteDriver: SqliteDriver
	private let logAggregator: LogAggregator
	private var config: JustTrackSdkConfig?
	private var pendingAdapters: [(JusttrackAdapter, FutureImpl<Void>)] = []

	private var isStarted = false

	/*
	 We do not support multiple calls of the start() method yet. Once we implement such support, we will remove this property.
	 */
	private var hasAlreadyBeenStarted = false

	convenience init(
		platformType: PlatformType,
		prefixedApiToken: String,
		attributionSettings: AttributionSettings,
		logger: Logger? = nil,
		httpClient: HttpClient? = nil,
		skAdNetwork: SkAdNetwork.Type?,
		clientId: String = Bundle.main.bundleIdentifier ?? "",
		applicationVersion: AppVersion = readAppVersion(),
		adTrackingEventPublisher: AdTrackingEventPublishing?,
		sqliteDriver: SqliteDriver? = nil,
		config: JustTrackSdkConfig? = nil,
		manualStart: Bool = false,
		isConsoleLoggingEnabled: Bool = true,
		serverUrl: URL? = nil
	) throws {
		let environmentSettings = EnvironmentSettings(
			prefixedApiToken: prefixedApiToken,
			serverUrl: serverUrl
		)

		let httpClient =
			httpClient
			?? HttpClientImpl(
				environment: environmentSettings.environment,
				platformType: platformType,
				appVersion: applicationVersion.name,
				apiToken: environmentSettings.apiToken,
				retryConfig: RetryConfig.defaultConfig,
				urlSession: URLSession.shared,
				clientId: clientId,
				isConsoleLoggingEnabled: isConsoleLoggingEnabled
			)

		var loggers = [Logger]()
		if let logger {
			loggers.append(logger)
		}
		if isConsoleLoggingEnabled {
			loggers.append(LoggerImpl())
		}

		let logger = CompositeLogger(loggers: loggers)

		try self.init(
			attributionSettings: attributionSettings,
			logger: logger,
			httpClient: httpClient,
			platformType: platformType,
			sessionManagerBuilder: { sdk in
				SessionManagerImpl(sdk)
			},
			connectivityManagerBuilder: { _ in
				do {
					return try ConnectivityManagerImpl()
				} catch {
					logger.error("Failed to initialize connectivity manager: \(error.justTrackGetErrorDescription())")
					return nil
				}
			},
			adTrackingProvider: AdTrackingProviderImpl.instance,
			skAdNetwork: skAdNetwork,
			bundleId: clientId,
			applicationVersion: applicationVersion,
			adTrackingEventPublisher: adTrackingEventPublisher ?? AdTrackingEventPublisher.shared,
			sqliteDriver: try sqliteDriver ?? DefaultSqliteDriver(),
			config: config ?? .default,
			manualStart: manualStart,
			isConsoleLoggingEnabled: isConsoleLoggingEnabled
		)
	}

	init(
		attributionSettings: AttributionSettings,
		logger: Logger,
		httpClient: HttpClient,
		platformType: PlatformType = .native,
		sessionManagerBuilder: (_ sdk: JustTrackSdkImpl) -> SessionManager,
		connectivityManagerBuilder: (_ sdk: JustTrackSdkImpl) -> ConnectivityManager?,
		adTrackingProvider: AdTrackingProvider,
		skAdNetwork: SkAdNetwork.Type?,
		claimsProvider: ClaimsProvider? = nil,
		crashReporter: CrashReporter = DefaultCrashReporter.shared,
		logAggregator: LogAggregator? = nil,
		bundleId: String? = nil,
		applicationVersion: AppVersion = readAppVersion(),
		adTrackingEventPublisher: AdTrackingEventPublishing,
		sqliteDriver: SqliteDriver,
		config: JustTrackSdkConfig,
		manualStart: Bool,
		isConsoleLoggingEnabled: Bool = true
	) throws {
		guard let resolvedBundleId = bundleId ?? Bundle.main.bundleIdentifier else {
			throw JustTrackError.missingBundleIdentifier
		}
		guard Thread.isMainThread else {
			throw JustTrackError.notOnMainThread
		}

		if !UserDefaults.standard.bool(forKey: Store.postbackConversionValueSetKey) {
			if #available(iOS 15.4, *) {
				skAdNetwork?.updatePostbackConversionValue(0, completionHandler: nil)
			} else if #available(iOS 11.3, *) {
				skAdNetwork?.registerAppForAdNetworkAttribution()
			}
		}

		self.bundleId = resolvedBundleId
		self.platformType = platformType
		self.applicationVersion = applicationVersion
		self.store = Store()
		self.appVersionUpdateInfo = self.store.getAppVersionUpdateInfo(currentVersion: applicationVersion)
		self.appVersionAtInstall = self.store.readAppVersionAtInstall(currentVersion: applicationVersion)
		self.store.setFirstSdkInitTimestamp(Date())
		self.reAttributionDecider = ChainedReAttributionDecider(
			ResolveOrganicAttributionDecider(),
			TimeBasedReAttributionDecider(inactivityTimeFrameHours: attributionSettings.inactivityTimeFrameHours, reAttributionTimeFrameDays: attributionSettings.reAttributionTimeFrameDays)
		)
		self.reFetchReAttributionDelay = TimeInterval(attributionSettings.reFetchReAttributionDelaySeconds)
		self.attributionRetryDelay = TimeInterval(attributionSettings.attributionRetryDelaySeconds)
		self.installId = store.getInstallId()
		self.adTrackingProvider = adTrackingProvider
		self.httpClient = httpClient
		let getAdIdsResult = FutureImpl<AdIds>()
		self.getAdIdsResult = getAdIdsResult
		let adIdsProviderWrapper = AdIdsProviderWrapper()
		self.logAggregator = logAggregator ?? LogAggregatorImpl(sqliteDriver: sqliteDriver, isConsoleLoggingEnabled: isConsoleLoggingEnabled)
		let httpLogger = HttpLoggerImpl(
			fallback: logger,
			httpClient: httpClient,
			logAggregator: self.logAggregator,
			installId: installId,
			adIdsProvider: adIdsProviderWrapper.provideAdIds,
			appVersionProvider: { applicationVersion }
		)
		self.adTrackingEventPublisher = adTrackingEventPublisher
		self.adIdsProviderWrapper = adIdsProviderWrapper
		self.logger = httpLogger
		self.adTrackingProvider.setLogger(self.logger)
		if let sdkConfig = store.getStoredOutput()?.sdkConfig {
			self.logger.setRules(logConfig: sdkConfig.log, metricConfig: sdkConfig.metric)
			self.httpClient.setRules(eventConfig: sdkConfig.event)
		}
		let currentInstallId = self.installId
		let store = self.store
		self.remoteConfig = RemoteConfigImpl(
			httpClient: httpClient,
			logger: httpLogger,
			sdkVersion: currentSdkVersion(),
			appVersion: applicationVersion,
			getInstallId: { currentInstallId },
			getAdIds: { getAdIdsResult.toFuture() },
			getDeviceInfo: { [adTrackingProvider] in DeviceInfo(idfvProvider: adTrackingProvider) },
			getAttributionTimestamp: { store.getAttributionTimestamps()?.firstAttributedAt },
			getFirstSdkInitTimestamp: { store.getFirstSdkInitTimestamp() },
			getInstallTimestamp: {
				guard let documentsUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first else {
					return nil
				}
				return (try? FileManager.default.attributesOfItem(atPath: documentsUrl.path)[.creationDate]) as? Date
			}
		)
		self.periodicLogsPublisher = PeriodicLogsPublisher(fallback: logger, httpLogger: self.logger)
		self.claimsProvider = claimsProvider ?? ClaimsProviderImpl(logger: self.logger)
		self.attributionCanRetryAt = nil
		self.attributionSubscriptions = SubscriptionManager()
		self.retargetingParamsSubscriptions = SubscriptionManager()
		self.preliminaryRetargetingParamsSubscriptions = SubscriptionManager()
		self.preliminaryRetargetingParametersImpl = nil
		self.delegateWatcher = AppDelegateWatcher()
		self.purchaseTracker = InAppPurchaseTrackerImpl(logger: self.logger)
		self.crashReporter = crashReporter
		if #available(iOS 14, *) {
			self.anrDetector = MetricKitAnrDetector(logger: self.logger)
		} else {
			self.anrDetector = DefaultAnrDetector(logger: self.logger)
		}
		self.sqliteDriver = sqliteDriver
		self.testGroupIdValue = precomputeTestGroupId()
		self.connectivityManager = connectivityManagerBuilder(self)
		self.userEventQueue = PublishEventsQueue(
			connectivityManager: self.connectivityManager,
			logger: httpLogger,
			publisher: self,
			sequenceNumberProvider: UserDefaultsSequenceNumberProvider(),
			sqliteDriver: sqliteDriver
		)
		self.sessionManager = sessionManagerBuilder(self)
		self.config = config

		httpLogger.sdkIsRunning = { [weak self] in
			self?.isRunning() ?? false
		}
		(self.remoteConfig as? RemoteConfigImpl)?.isRunning = { [weak self] in
			self?.isRunning() ?? false
		}

		anrDetector.setHandler { [weak self, weak anrDetector] report in
			guard let self else {
				anrDetector?.removeHandler()
				return
			}
			self.logger.error("App is unresponsive! \(report.errorFields.getFields())")
		}

		if !manualStart {
			start()
		}

		#if DEBUG
			sdkBridge = SdkBridge(
				sdk: self,
				httpLogger: self.logger,
				getAdIdsResult: getAdIdsResult
			)
		#endif
	}

	static func computeTestGroupId(idfv: String) -> Int? {
		if idfv.count < 3 {
			return nil
		}

		guard let idfvNumber = Int(idfv.suffix(3), radix: 16) else {
			return nil
		}

		return (idfvNumber % 3) + 1
	}

	func anonymize() -> Future<Void> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}
		let result = FutureImpl<Void>()
		getAdIds().observe { [httpClient] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				result.reject(error)
			case let .success(adIds):
				let deviceInfo = DeviceInfo(idfvProvider: self.adTrackingProvider)
				let request = DTOAnonymizeRequest(
					installInstanceId: self.installId,
					deviceId: adIds.idfa,
					idfv: deviceInfo.idfv
				)
				let userData = UserData(
					idfa: adIds.idfa,
					userId: adIds.userId,
					installId: self.installId
				)
				httpClient.sendAnonymizeRequest(request: request, userData: userData).observe { anonymizeResult in
					switch anonymizeResult {
					case let .failure(error):
						result.reject(error)
					case .success:
						result.resolve(Void())
					}
				}
			}
		}
		return result.toFuture()
	}

	func isRunning() -> Bool {
		objc_sync_enter(self)
		defer { objc_sync_exit(self) }
		return isStarted
	}

	func register(attributionListener listener: @escaping (AttributionResponse) -> Void) -> Subscription {
		return attributionSubscriptions.subscribe(listener: listener)
	}

	func register(retargetingParametersListener listener: @escaping (RetargetingParameters) -> Void) -> Subscription {
		return retargetingParamsSubscriptions.subscribe(listener: listener)
	}

	func register(preliminaryRetargetingParametersListener listener: @escaping (PreliminaryRetargetingParameters) -> Void) -> Subscription {
		return preliminaryRetargetingParamsSubscriptions.subscribe(listener: listener)
	}

	func shutdown() {
		moveToBackground()
		sessionManager = nil
		delegateWatcher.uninstall()
		periodicLogsPublisher.stop()
		userEventQueue?.shutdown()
		connectivityManager?.shutdown()
		connectivityManager = nil
		crashReporter.stopMonitoring()
	}

	func set(userId customUserId: String) -> Future<Void> {
		if !isValid(customUserId: customUserId) {
			let error = InvalidFieldError(name: "customUserId", value: customUserId, minLength: 1, maxLength: 4096, encoding: "ASCII")
			logger.error("Not publishing invalid custom user id: \(error)")

			return FutureImpl().reject(error)
		}

		if !CustomUserIdStore.storeNewId(installId: lastInstallId, customUserId: customUserId) {
			let fields = LoggerFieldsImpl().with("customUserId", customUserId)
			logger.debug("Not publishing a custom user id twice", fields)

			return FutureImpl<Void>().resolve(Void())
		}

		return performCustomUserIdSend(customUserId, reason: "send")
	}

	func set(firebaseAppInstanceId: String) -> Future<Void> {
		if !isValid(firebaseAppInstanceId: firebaseAppInstanceId) {
			let error = InvalidFieldError(
				name: "firebaseAppInstanceId",
				value: firebaseAppInstanceId,
				minLength: 8,
				maxLength: 256,
				encoding: "ASCII"
			)
			logger.error("Not publishing invalid Firebase app instance id: \(error)")

			return FutureImpl().reject(error)
		}

		self.firebaseAppInstanceId = firebaseAppInstanceId

		let result = FutureImpl<Void>()
		let fields = LoggerFieldsImpl().with("firebaseAppInstanceId", firebaseAppInstanceId)

		getAdIds().observe { [weak self] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				self?.logger.error("Failed to get idfa", fields.with("exception", error))
				result.reject(error)
			case let .success(adIds):
				self?.set(firebaseAppInstanceId: firebaseAppInstanceId, adIds: adIds, fields: fields, result: result)
				result.resolve(())
			}
		}

		return result.toFuture()
	}

	private func set(
		firebaseAppInstanceId: String,
		adIds: AdIds,
		fields: LoggerFieldsBuilder,
		result: FutureImpl<Void>
	) {
		logger.info("Publishing new Firebase app instance id", fields)
		let body = DTOPublishFirebaseAppInstanceIdRequest(uuid: adIds.userId.value, firebaseInstanceId: firebaseAppInstanceId)
		httpClient.sendFirebaseAppInstanceId(
			request: body,
			userData: UserData(
				idfa: adIds.idfa,
				userId: adIds.userId,
				installId: installId
			)
		).observe { response in
			switch response {
			case .failure(let error):
				self.logger.error("Failed to publish new Firebase app instance id", fields.with("exception", error))
				_ = result.reject(error)
			case .success:
				_ = result.resolve(Void())
			}
		}
	}

	func set(odmInfo: String) -> Future<Void> {
		let fields = LoggerFieldsImpl().with("odmInfo", odmInfo)

		if self.odmInfo == odmInfo {
			logger.debug("Not publishing ODM info twice", fields)
			return FutureImpl<Void>().resolve(Void())
		}

		self.odmInfo = odmInfo
		logger.info("Setting new ODM info, triggering re-attribution", fields)

		return TransformingFuture(getAttributionOutput(forcedDecision: .fetchAttributionAfterGettingIdfa)) { _ in
			Void()
		}.toFuture()
	}

	func set(automaticInAppPurchaseTracking: Bool) {
		self.purchaseTracker.set(enabled: automaticInAppPurchaseTracking)
	}

	func start() {
		start(config: config)
	}

	func start(config: JustTrackSdkConfig?) {
		objc_sync_enter(self)
		guard !isStarted else {
			objc_sync_exit(self)
			return
		}
		guard !hasAlreadyBeenStarted else {
			isStarted = true
			objc_sync_exit(self)
			logger.getFallback().warn(
				"The justtrack SDK does not currently support multiple starts with different configurations. The SDK has been started again, but it continues to use the previously set configuration.",
				LoggerFieldsImpl()
			)
			return
		}
		isStarted = true
		hasAlreadyBeenStarted = true
		objc_sync_exit(self)

		let config = config ?? .default
		self.config = config

		if let userId = config.userId {
			_ = set(userId: userId)
		}

		if let trackingInfo = config.trackingInfo {
			trackingId = trackingInfo.id
			trackingProvider = trackingInfo.provider
		}

		integrateWithAdjoe()

		for (adapter, promise) in pendingAdapters {
			adapter.integrate(sdk: self, logger: logger).observe { result in
				switch result {
				case let .failure(error):
					promise.reject(error)
				case .success:
					promise.resolve(())
				}
			}
		}
		pendingAdapters.removeAll()

		self.sessionManager?.start()
		purchaseTracker.start(sdk: self)
		delegateWatcher.reportee = self
		_ = self.connectivityManager?.registerOnReconnect(self.onReconnect)
		self.lastInstallId = getCachedAttribution()?.installId
		adIdsProviderWrapper?.adIdsProvider = self

		JustTrack.setSdk(self)
		retrySendCustomUserId(reason: "app start")
		#if DEBUG
			self.logger.debug("Initializing SDK with version \(sdkVersion.name)", LoggerFieldsImpl())
		#endif

		_ = getAttributionOutput(forcedDecision: nil)

		// We set the observer to get the most relevant ATT authorization status.
		//
		// Once we set an observer, the publisher notifies the observer of the current ATT status via the methods of the `AdTrackingEventPublisherObserver` protocol.
		adTrackingEventPublisher?.set(observer: self)

		crashReporter.checkJsReport { [weak self] result in
			guard let self else { return }
			switch result {
			case let .success(report):
				let fields = LoggerFieldsImpl()
					.with("message", report.message)
					.with("stack_trace", report.stackTrace)
					.with("timestamp", formatDateMilliseconds(report.timestamp))
				self.logger.publishMetric(Metric(metric: "crash"), 1, fields)
				self.logger.error("A JS crash report received", fields)
			case let .failure(error):
				self.logger.error(
					"An error during retrieving a JS crash report received",
					LoggerFieldsImpl()
						.with("description", error.justTrackGetErrorDescription())
				)
			}
		}

		crashReporter.checkNativeCrashReport { [weak self] result in
			guard let self else { return }
			switch result {
			case let .success(report):
				switch report.reportType {
				case .exception:
					let exceptionReport = CrashReport.ExceptionReport(
						name: report.name,
						reason: report.reason,
						callStack: report.callStack
					)
					self.logger.publishMetric(
						Metric(metric: "crash"),
						1,
						exceptionReport.metricFields
					)
					self.logger.error(
						"Application shutdown due to crash at \(report.timestamp)",
						exceptionReport.generateErrorFields(breadcrumbs: self.logAggregator.getBreadcrumbs())
					)
				case .signal:
					let signalInfo = report.signalInfo.map { storedInfo in
						CrashReport.SignalReport.Info(
							errorNumber: storedInfo.errorNumber,
							signalCode: storedInfo.signalCode,
							signalNumber: storedInfo.signalNumber,
							sendingProcess: storedInfo.sendingProcess,
							senderRuid: storedInfo.senderRuid,
							exitValue: storedInfo.exitValue,
							signalValue: storedInfo.signalValue,
							faultingAddress: storedInfo.faultingAddress
						)
					}
					let signalReport = CrashReport.SignalReport(
						name: report.name,
						callStack: report.callStack,
						info: signalInfo
					)
					self.logger.publishMetric(
						Metric(metric: "crash"),
						1,
						LoggerFieldsImpl()
							.with("signal_name", signalReport.name)
					)
					self.logger.error(
						"Application shutdown due to crash at \(report.timestamp)",
						signalReport.generateErrorFields(breadcrumbs: self.logAggregator.getBreadcrumbs())
					)
				}
			case let .failure(error):
				self.logger.error(
					"An error during retrieving a native crash report received",
					LoggerFieldsImpl()
						.with("description", error.justTrackGetErrorDescription())
				)
			}
		}

		crashReporter.startMonitoring()
	}

	func stop() {
		objc_sync_enter(self)
		defer { objc_sync_exit(self) }

		isStarted = false
	}

	@available(*, deprecated, renamed: "track")
	@discardableResult
	func publish(event: AppEvent) -> Future<Void> {
		track(event: event)
	}

	@discardableResult
	func track(event: AppEvent) -> Future<Void> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}

		guard let sessionManager else {
			return FutureImpl().reject(SdkShutdownError())
		}

		let builder = event

		do {
			try builder.validate()
		} catch {
			logger.error("Not publishing invalid user event: \(error)")

			return FutureImpl().reject(error)
		}

		let buildEvent = builder.build(sessionId: sessionManager.getLastSessionId(self))
		sessionManager.saveSession()

		return getUserEventQueue().publishEvent(event: buildEvent)
	}

	@discardableResult
	func forward(adImpression: AdImpression) -> Future<Void> {
		let result = FutureImpl<Void>()

		guard isRunning() else {
			return result.reject(JustTrackError.stopped)
		}

		return forward(adImpression: adImpression, extraDimensions: [:])
	}

	func getInstallInstanceId() -> Future<String> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}
		return FutureImpl().resolve(installId.value)
	}

	func getAdvertiserIdInfo() -> Future<AdvertiserIdInfo> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}
		return TransformingFuture(getAdIds()) { adIds in
			AdvertisingIdInfoImpl(advertiserId: adIds.idfa?.value)
		}.toFuture()
	}

	func setExperimentVariant(experiment: String, variant: String, tags: [String], happenedAt: Date?) -> Future<Void> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}

		guard experiment.count > 0 && experiment.count <= 256 && experiment.isASCII else {
			let error = InvalidFieldError(name: "experiment", value: experiment, minLength: 1, maxLength: 256, encoding: "ASCII")
			logger.error("Not setting experiment variant with invalid experiment: \(error)")
			return FutureImpl().reject(error)
		}
		guard variant.count > 0 && variant.count <= 256 && variant.isASCII else {
			let error = InvalidFieldError(name: "variant", value: variant, minLength: 1, maxLength: 256, encoding: "ASCII")
			logger.error("Not setting experiment variant with invalid variant: \(error)")
			return FutureImpl().reject(error)
		}

		guard tags.count <= 5 else {
			let error = JustTrackError.custom("Invalid tags: array exceeds maximum of 5 elements (provided: \(tags.count))")
			logger.error("Not setting experiment variant with too many tags: \(error)")
			return FutureImpl().reject(error)
		}

		for (index, tag) in tags.enumerated() {
			guard tag.count > 0 && tag.count <= 64 && tag.isASCII else {
				let error = InvalidFieldError(name: "tags[\(index)]", value: tag, minLength: 1, maxLength: 64, encoding: "ASCII")
				logger.error("Not setting experiment variant with invalid tag: \(error)")
				return FutureImpl().reject(error)
			}
		}

		let request = DTOSetExperimentVariantRequest(
			installId: installId,
			sdkVersion: sdkVersion,
			appVersion: appVersionAtInstall,
			osVersion: DeviceInfo(idfvProvider: adTrackingProvider).osVersion,
			experiment: experiment,
			variant: variant,
			tags: tags,
			happenedAt: happenedAt
		)

		let fields = LoggerFieldsImpl()
			.with("experiment", experiment)
			.with("variant", variant)
			.with("tags", tags.joined(separator: ","))

		logger.info("Sending experiment variant assignment", fields)

		let result = FutureImpl<Void>()

		getAdIds().observe { [weak self] adIdsResult in
			guard let self else {
				result.reject(JustTrackError.custom("SDK instance deallocated"))
				return
			}

			switch adIdsResult {
			case let .failure(error):
				self.logger.error("Failed to get ad ids for experiment variant assignment", fields.with("error", error))
				result.reject(error)

			case let .success(adIds):
				self.httpClient.sendSetExperimentVariant(
					request: request,
					userData: UserData(
						idfa: adIds.idfa,
						userId: adIds.userId,
						installId: self.installId
					)
				).observe { response in
					switch response {
					case let .failure(error):
						self.logger.error("Failed to send experiment variant assignment", fields.with("error", error))
						result.reject(error)
					case .success:
						self.logger.info("Successfully sent experiment variant assignment", fields)
						result.resolve(Void())
					}
				}
			}
		}

		return result.toFuture()
	}

	@available(iOS 15.0, *)
	@discardableResult
	func forward(transaction: Transaction) -> Result<Void, Error> {
		guard isRunning() else {
			return .failure(JustTrackError.stopped)
		}
		InAppPurchaseHandler.shared.report(on: transaction, sdk: self, logger: logger)
		return .success(Void())
	}

	@available(iOS 15.0, *)
	@discardableResult
	func forward(transactionId: String, productId: String, quantity: Int) -> Result<Void, Error> {
		guard isRunning() else {
			return .failure(JustTrackError.stopped)
		}
		guard let transactionId = UInt64(transactionId) else {
			return .failure(JustTrackError.custom("Wrong transactionId"))
		}
		InAppPurchaseHandler.shared.reportOnTransactionId(transactionId, productId: productId, quantity: quantity, sdk: self, logger: logger)
		return .success(Void())
	}

	@discardableResult
	func integrate(with adapter: JusttrackAdapter) -> Future<Void> {
		if isRunning() {
			return adapter.integrate(sdk: self, logger: logger)
		}

		let promise = FutureImpl<Void>()
		pendingAdapters.append((adapter, promise))
		return promise.toFuture()
	}

	func getUserEventQueue() -> PublishEventsQueue {
		guard let userEventQueue = userEventQueue else {
			// should normally not happen, but if it happens, just setup the queue and use it
			let userEventQueue = PublishEventsQueue(
				connectivityManager: self.connectivityManager,
				logger: logger,
				publisher: self,
				sequenceNumberProvider: UserDefaultsSequenceNumberProvider(),
				sqliteDriver: sqliteDriver
			)
			self.userEventQueue = userEventQueue

			return userEventQueue
		}

		return userEventQueue
	}

	func publishEventBatch(batch: PublishingBatch) -> Future<Void> {
		let result = FutureImpl<Void>()

		getAdIds().observe { [weak self] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				self?.logger.error("Failed to get idfa", LoggerFieldsImpl().with("exception", error))

			case let .success(adIds):
				self?.publishEventBatch(batch: batch, adIds: adIds, result: result)
			}
		}

		return result.toFuture()
	}

	private func publishEventBatch(
		batch: PublishingBatch,
		adIds: AdIds,
		result: FutureImpl<Void>
	) {
		attribution.observe { [weak self] attribution in
			guard let self else { return }

			switch attribution {
			case let .failure(error):
				self.logger.debug("Not publishing events batch, attribution failed", LoggerFieldsImpl().with("exception", error))
				_ = result.reject(error)

			case .success:
				let events = PublishableUserEvent.build(
					batch: batch,
					idfa: adIds.idfa?.value,
					userId: adIds.userId,
					installId: self.installId,
					idfvProvider: self.adTrackingProvider,
					applicationVersion: self.applicationVersion,
					platformType: self.platformType
				)
				let request = self.httpClient.sendUserEvents(
					events: events,
					userData: UserData(
						idfa: adIds.idfa,
						userId: adIds.userId,
						installId: self.installId
					)
				)
				request.observe { eventResponse in
					switch eventResponse {
					case let .failure(error):
						self.logger.debug(
							"Publishing events in batch failed",
							LoggerFieldsImpl()
								.with("exception", error.justTrackGetErrorDescription())
						)
						_ = result.reject(error)
					case .success:
						#if DEBUG
							for event in batch.events {
								self.logger.getFallback().debug("Successfully published \(event.baseEvent()) at \(event.happenedAt()) in batch")
							}
						#endif
						_ = result.resolve(Void())
					}
				}
			}
		}
	}

	func spawnFetchClaimTask(ipProtocol: IPProtocol) -> Future<String> {
		let result = FutureImpl<String>()
		let connectionType = getNetworkType()
		let start = Date()

		getAdIds().observe { [weak self] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				self?.logger.error("Failed to get idfa", LoggerFieldsImpl().with("exception", error))

			case let .success(adIds):
				self?.spawnFetchClaimTask(ipProtocol: ipProtocol, adIds: adIds, connectionType: connectionType, start: start, result: result)
			}
		}

		return result.toFuture()
	}

	private func spawnFetchClaimTask(
		ipProtocol: IPProtocol,
		adIds: AdIds,
		connectionType: ConnectionType,
		start: Date,
		result: FutureImpl<String>
	) {
		httpClient.getSignedIpClaim(
			ipProtocol: ipProtocol,
			userData: UserData(
				idfa: adIds.idfa,
				userId: adIds.userId,
				installId: installId
			)
		).observe { response in
			switch response {
			case .failure(let error):
				_ = result.reject(error)
			case .success(let responseData):
				do {
					let response = try DTOSignIPResponse(data: responseData)
					let timeTaken = Date().timeIntervalSince(start)
					let dimensions = LoggerFieldsImpl().with("Network", connectionType.stringValue)
					self.logger.publishMetric(ipProtocol.claimDurationMetric, timeTaken, dimensions)
					self.logger.debug("Got IP claim", LoggerFieldsImpl().with("ip", response.ip).with("type", response.type))
					_ = result.resolve(response.token)
				} catch {
					_ = result.reject(error)
				}
			}
		}
	}

	func integrateWithAdjoe() {
		AdjoeIntegration.performIntegration(
			{ (adUnit, adNetwork, placement, appId) in
				let unit: AdUnit?
				switch adUnit {
				case "BANNER":
					unit = .banner
				case "VIDEO_INTERSTITIAL":
					unit = .interstitial
				case "VIDEO_REWARDED":
					unit = .rewarded
				default:
					unit = nil
				}
				guard let unit = unit else {
					self.logger.error("Adjoe event contained invalid ad format", LoggerFieldsImpl().with("adUnit", adUnit))
					return
				}
				let impression = AdImpression(unit: unit, sdkName: "adjoe")
					.set(network: adNetwork)
					.set(placement: placement)
					.set(bundleId: appId)
				self.forward(adImpression: impression).observe { forwardResult in
					switch forwardResult {
					case let .failure(error):
						self.logger.error("Could not publish Adjoe impression", LoggerFieldsImpl().with("adUnit", adUnit).with("error", error.justTrackGetErrorDescription()))
					case .success:
						break
					}
				}
			},
			{ (message, version) in
				guard let version = version else {
					self.logger.debug("Could not integrate with Adjoe (not found)", LoggerFieldsImpl().with("message", message))
					return
				}
				self.logger.error("Could not integrate with Adjoe", LoggerFieldsImpl().with("message", message).with("version", version))
			},
			{ version in
				self.logger.info("Completed integration with Adjoe", LoggerFieldsImpl().with("version", version))
			}
		)
	}

	func forwardInAppPurchase(transactionId: String?, productId: String, totalPrice: Money) -> Bool {
		if totalPrice.value < 0 {
			logger.warn(
				"Negative revenue for product purchase",
				LoggerFieldsImpl()
					.with("productId", productId)
					.with("revenue", totalPrice.value)
					.with("currency", totalPrice.currency)
			)

			return false
		}

		do {
			try totalPrice.validate()
		} catch {
			logger.warn("Not publishing invalid product purchase: \(error)", LoggerFieldsImpl().with("productId", productId))

			return false
		}

		_ = track(
			event: JtPurchaseInternalEvent(
				jtAction: "success",
				jtProductId: productId,
				jtToken: transactionId ?? readReceiptData() ?? "",
				jtProductType: "purchase",
				revenue: totalPrice,
				happenedAt: Date()
			)
		)

		return true
	}

	func forwardInAppPurchase(transactionId: String?, subscriptionId: String, totalPrice: Money) -> Bool {
		if totalPrice.value < 0 {
			logger.warn(
				"Negative revenue for subscription purchase",
				LoggerFieldsImpl()
					.with("subscriptionId", subscriptionId)
					.with("revenue", totalPrice.value)
					.with("currency", totalPrice.currency)
			)

			return false
		}

		do {
			try totalPrice.validate()
		} catch {
			logger.warn("Not publishing invalid subscription purchase: \(error)", LoggerFieldsImpl().with("subscriptionId", subscriptionId))

			return false
		}

		_ = track(
			event: JtPurchaseInternalEvent(
				jtAction: "success",
				jtProductId: subscriptionId,
				jtToken: transactionId ?? readReceiptData() ?? "",
				jtProductType: "subscription",
				revenue: totalPrice,
				happenedAt: Date()
			)
		)

		return true
	}

	func notifyAppStart(_ event: AppStateEvent) {
		guard let sessionManager = sessionManager else { return }
		let sessionId = sessionManager.getLastSessionId(self)
		let duration = event.startingTook
		let happenedAt = event.startedAt
		_ = track(event: JtAppOpenEvent(sessionId: sessionId, duration: duration, unit: .milliseconds, happenedAt: happenedAt))
		switch appVersionUpdateInfo.kind {
		case .installedApp:
			_ = track(event: JtAppInstallEvent(sessionId: sessionId, duration: duration, unit: .milliseconds, happenedAt: happenedAt))
		case .updatedApp:
			let previousVersion = appVersionUpdateInfo.lastAppVersion.name
			logger.info("App was updated", LoggerFieldsImpl().with("previous_app_version_code", previousVersion))
		case .noChange:
			// no change
			break
		}
	}

	func moveToForeground() {
		sessionManager?.moveToForeground()
		periodicLogsPublisher.start()
	}

	func moveToBackground() {
		sessionManager?.moveToBackground()
		periodicLogsPublisher.pause()
		logAggregator.moveToBackground()
		userEventQueue?.moveToBackground()
	}

	func applicationWillTerminate() {
		sessionManager?.saveSession()
		shutdown()
	}

	private func precomputeTestGroupId() -> Int? {
		let deviceInfo = DeviceInfo(idfvProvider: adTrackingProvider)
		let idfv = deviceInfo.idfv?.value ?? ""
		if let (testGroupId, needsToRestore) = store.getTestGroupId(idfv: idfv) {
			if needsToRestore {
				store.setTestGroupId(idfv: idfv, testGroupId: testGroupId)
			}

			return testGroupId
		}

		let testGroupId = Self.computeTestGroupId(idfv: idfv)
		store.setTestGroupId(idfv: idfv, testGroupId: testGroupId)

		return testGroupId
	}

	func getAdIds() -> Future<AdIds> {
		return getAdIdsResult.toFuture()
	}

	private func attributionIsOldFail() -> Bool {
		guard let attributionCanRetryAt = attributionCanRetryAt else {
			return false
		}

		return attributionCanRetryAt < Date()
	}

	private func getAttributionOutput(forcedDecision: AttributionDecision?) -> Future<AttributionOutput> {
		guard isRunning() else {
			return FutureImpl().reject(JustTrackError.stopped)
		}

		objc_sync_enter(self)
		defer { objc_sync_exit(self) }

		if forcedDecision == nil {
			if let response = attributionOutput {
				if attributionIsOldFail() {
					attributionCanRetryAt = nil
					attributionOutput = nil
					logger.debug("Retrying old failed attribution")
				} else {
					return response
				}
			}
		}

		let attributionTimestamps = store.getAttributionTimestamps()
		// after getting the last timestamps we can write into the store our open timestamp so we know the
		// next time whether the user opened the app not for quite some time
		store.setLastOpen()

		let attributionDecision = forcedDecision ?? reAttributionDecider.needsReAttribution(attributionTimestamps: attributionTimestamps)
		let storedOutput = store.getStoredOutput()

		if !attributionDecision.shouldFetchAttribution {
			if let storedOutput {
				let storedResponse = storedOutput.attributionResponse
				let attributionOutput = FutureImpl(storedOutput).toFuture()
				self.attributionOutput = attributionOutput
				if let sdkConfig = storedOutput.sdkConfig {
					logger.setRules(logConfig: sdkConfig.log, metricConfig: sdkConfig.metric)
					httpClient.setRules(eventConfig: sdkConfig.event)
				}
				logger.debug("Using cached attribution")
				attributionSubscriptions.call(value: storedResponse)
				return attributionOutput
			}
		}

		let attributionStart = Date()
		let connectionType = getNetworkType()
		let attributionOutputPromise = FutureImpl<AttributionOutput>()
		let attributionOutput = attributionOutputPromise.toFuture()
		self.attributionOutput = attributionOutput

		getAdIds().observe { [weak self] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				self?.logger.error("Failed to get idfa", LoggerFieldsImpl().with("exception", error))

			case let .success(adIds):
				self?.getAttributionOutput(
					forcedDecision: forcedDecision,
					adIds: adIds,
					attributionDecision: attributionDecision,
					attributionOutputPromise: attributionOutputPromise,
					attributionOutput: attributionOutput,
					attributionStart: attributionStart,
					connectionType: connectionType,
					attributionTimestamps: attributionTimestamps,
					storedOutput: storedOutput
				)
			}
		}

		return attributionOutput
	}

	private func getAttributionOutput(
		forcedDecision: AttributionDecision?,
		adIds: AdIds,
		attributionDecision: AttributionDecision,
		attributionOutputPromise: FutureImpl<AttributionOutput>,
		attributionOutput: Future<AttributionOutput>,
		attributionStart: Date,
		connectionType: ConnectionType,
		attributionTimestamps: AttributionTimestamps?,
		storedOutput: AttributionOutput?
	) {
		let deviceInfo = DeviceInfo(idfvProvider: adTrackingProvider)
		let user = DTOAttributionRequestUser(
			userId: adIds.userId,
			installInstanceId: installId,
			idfv: deviceInfo.idfv,
			idfa: adIds.idfa,
			hasLimitedAdTracking: adIds.idfa == nil,
			trackingId: trackingId,
			trackingProvider: trackingProvider,
			countryIso: getCurrentCountry()
		)
		let device = DTOAttributionRequestDevice(
			name: deviceInfo.name,
			model: deviceInfo.model,
			product: deviceInfo.product,
			type: deviceInfo.type,
			os: DTOAttributionRequestDeviceOS(version: deviceInfo.osVersion, name: deviceInfo.osName),
			display: DTOAttributionRequestDeviceDisplay(width: deviceInfo.displayWidth, height: deviceInfo.displayHeight)
		)
		claimsProvider.refreshClaims(sdk: self)
		claimsProvider.provideClaims(timeout: attributionDecision.getClaimsTimeout()) { (claims, didTimeOut) in
			var parameters: [String: String] = [:]

			// for some reason, the following hangs in the simulator. We don't really need it there anyway.
			#if !targetEnvironment(simulator)
				if #available(iOS 14.3, *) {
					do {
						let token = try AAAttribution.attributionToken()
						parameters["appleSearchAdsToken"] = token
					} catch {
						self.logger.error("Failed to lookup apple search ads token", LoggerFieldsImpl().with("error", error))
					}
				}
			#endif

			if let odmInfo = self.odmInfo {
				parameters["odmInfo"] = odmInfo
			}

			let request = DTOAttributionRequest(
				appVersion: DTOAppVersion(self.applicationVersion),
				sdkVersion: DTOSdkVersion(currentSdkVersion()),
				user: user,
				device: device,
				claims: claims,
				parameters: parameters
			)
			self.httpClient.sendAttributionRequest(
				request: request,
				userData: UserData(idfa: adIds.idfa, userId: adIds.userId, installId: self.installId)
			).observe { result in
				switch result {
				case .failure(let error):
					_ = attributionOutputPromise.reject(error)
				case .success(let responseData):
					do {
						let response = try DTOAttributionResponse(userId: adIds.userId, data: responseData, wasAlreadyInstalled: false)

						let sdkConfig = (try? JSONDecoder().decode(AttributionOutputSdkConfigContainer.self, from: responseData))?.sdkConfig
						if let sdkConfig {
							self.logger.setRules(logConfig: sdkConfig.log, metricConfig: sdkConfig.metric)
							self.httpClient.setRules(eventConfig: sdkConfig.event)
						}

						objc_sync_enter(self)
						self.installId = response.installId
						let output = AttributionOutput(
							completeAttributionResponse: response,
							retargetingParameters: response.retargetingParameters,
							testGroup: response.userTestGroup,
							claimsTimedOut: didTimeOut,
							sdkConfig: sdkConfig
						)
						self.store.storeAttribution(attribution: output)
						self.store.setTestGroupId(idfv: user.deviceId, testGroupId: output.testGroup)
						self.testGroupIdValue = output.testGroup
						objc_sync_exit(self)

						_ = attributionOutputPromise.resolve(output)
					} catch {
						_ = attributionOutputPromise.reject(error)
					}
				}
			}
		}

		attributionOutput.observe { result in
			switch result {
			case .failure(let error):
				switch RetryingFuture<Data>.classifyError(error: error, errorClassifier: AttributionErrorClassifier()) {
				case .recoverable(let waitTime):
					// retry only after at least the wait time is over
					self.attributionCanRetryAt = Date(timeIntervalSinceNow: max(self.attributionRetryDelay, waitTime))
				case .retryDefault:
					self.attributionCanRetryAt = Date(timeIntervalSinceNow: self.attributionRetryDelay)
				case .unrecoverable:
					// use an hour as "infinity" - if the app is still running after 1h, we can take the hit, if not, we don't leave the chance
					// that something lingers in memory and the next time we run we can't handle this
					self.attributionCanRetryAt = Date(timeIntervalSinceNow: 3600)
				}
				self.logger.error("Failed to get attribution", error)
			case .success(let response):
				self.logger.set(installId: response.completeAttributionResponse.installId)
				let attributionDuration = Date().timeIntervalSince(attributionStart)
				let networkDimension = LoggerFieldsImpl().with("Network", connectionType.stringValue)
				self.logger.publishMetric(Self.attributionDurationMetric, attributionDuration, networkDimension)
				self.onAttributionDone(response)

				self.attributionCanRetryAt = nil
				if let attributionTimestamps {
					if !attributionDecision.shouldFetchAttribution {
						self.logger.info("Attribution was not needed, but was not cached")
					} else {
						let attributionAge = attributionTimestamps.lastAttributedAt.timeIntervalSince(attributionTimestamps.firstAttributedAt)
						let now = Date()
						let sinceLastOpen = now.timeIntervalSince(attributionTimestamps.lastOpenAt)
						let sinceLastAttribution = now.timeIntervalSince(attributionTimestamps.lastAttributedAt)
						let fields = LoggerFieldsImpl()
							.with("attributionAge", attributionAge)
							.with("sinceLastOpen", sinceLastOpen)
							.with("sinceLastAttribution", sinceLastAttribution)
							.with("force", forcedDecision != nil)
						self.logger.debug("Attribution was fetched again because re-attribution was needed", fields)
					}
				} else {
					self.logger.debug("Fetched first attribution")
				}
				self.attributionSubscriptions.call(value: response.attributionResponse)
				self.callRetargetingParametersSubscriptions(retargetingParameters: response.retargetingParameters)

				let needsClaimRefetch = response.attributionResponse.campaign.isOrganic && response.claimsTimedOut && attributionDecision.isFastClaimsTimeout()
				let needsReAttribution =
					attributionDecision.isFetchRetargetingAttribution()
					&& self.hasOldInstallId(
						storedResponse: storedOutput?.completeAttributionResponse,
						newResponse: response
					) && self.reFetchReAttributionDelay > 0

				// check if we expected a re-attribution and did not get one
				if needsReAttribution {
					self.fetchAttributionAgainAfter(
						message: needsClaimRefetch
							? "Fetching attribution again (with longer claims timeout) because the retargeting delay expired and previously the attribution did not change"
							: "Fetching attribution again because the retargeting delay expired and previously the attribution did not change",
						forcedDecision: needsClaimRefetch
							? AttributionDecision.fetchRetargetingAttributionDelayed.withSlowClaimsTimeout()
							: AttributionDecision.fetchRetargetingAttributionDelayed,
						delay: self.reFetchReAttributionDelay
					)
				} else {
					if let preliminaryRetargetingParametersImpl = self.preliminaryRetargetingParametersImpl {
						_ = preliminaryRetargetingParametersImpl.resolve(response)
					}
					if needsClaimRefetch {
						self.fetchAttributionAgainAfter(
							message: "Fetching attribution again with longer timeout while waiting for claims",
							forcedDecision: AttributionDecision.fetchFirstAttribution.withSlowClaimsTimeout(),
							delay: 3  // we don't really need to wait for a long time before trying again
						)
					}
				}
			}
		}
	}

	private func hasOldInstallId(storedResponse: CompleteAttributionResponse?, newResponse: AttributionOutput) -> Bool {
		guard let storedResponse = storedResponse else {
			return true
		}

		return storedResponse.installId == newResponse.completeAttributionResponse.installId
	}

	private func onAttributionDone(_ output: AttributionOutput) {
		let installId = output.completeAttributionResponse.installId

		objc_sync_enter(self)
		if installId == lastInstallId {
			objc_sync_exit(self)

			return
		}

		lastInstallId = installId
		objc_sync_exit(self)

		onInstallIdChange(installId)
	}

	private func onInstallIdChange(_ installId: StringID) {
		if let customUserId = CustomUserIdStore.getPendingWithNewInstallId(installId: installId) {
			_ = performCustomUserIdSend(customUserId, reason: "installId changed")
		}
		if let firebaseAppInstanceId = firebaseAppInstanceId {
			_ = set(firebaseAppInstanceId: firebaseAppInstanceId)
		}
	}

	private func fetchAttributionAgainAfter(message: String, forcedDecision: AttributionDecision, delay: TimeInterval) {
		DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
			self.logger.info(message)
			_ = self.getAttributionOutput(forcedDecision: forcedDecision)
		}
	}

	private func onReconnect() {
		self.retryAttributionAfterReconnect()
		self.retrySendCustomUserId(reason: "reconnect")
	}

	private func retryAttributionAfterReconnect() {
		guard attributionCanRetryAt != nil else { return }
		attributionOutput = nil
		attributionCanRetryAt = nil
		logger.info("Fetching attribution again as it failed and we got a new network connection")
		_ = getAttributionOutput(forcedDecision: AttributionDecision.fetchFirstAttribution)
	}

	private func retrySendCustomUserId(reason: String) {
		guard let pendingCustomUserId = CustomUserIdStore.getPendingId() else { return }
		_ = performCustomUserIdSend(pendingCustomUserId, reason: reason)
	}

	private func callRetargetingParametersSubscriptions(retargetingParameters: RetargetingParameters?) {
		guard let retargetingParameters = retargetingParameters else { return }

		retargetingParamsSubscriptions.call(value: retargetingParameters)
	}

	private func getCachedAttribution() -> CompleteAttributionResponse? {
		return store.getStoredOutput()?.completeAttributionResponse
	}

	private func performCustomUserIdSend(_ customUserId: String, reason: String) -> Future<Void> {
		let result = FutureImpl<Void>()
		let fields = LoggerFieldsImpl().with("customUserId", customUserId).with("reason", reason)

		getAdIds().observe { [weak self] adIdsResult in
			switch adIdsResult {
			case let .failure(error):
				self?.logger.error("Failed to get idfa", fields.with("exception", error))

			case let .success(adIds):
				self?.performCustomUserIdSend(
					customUserId: customUserId,
					adIds: adIds,
					fields: fields,
					result: result
				)
			}
		}

		return result.toFuture()
	}

	private func performCustomUserIdSend(
		customUserId: String,
		adIds: AdIds,
		fields: LoggerFieldsBuilder,
		result: FutureImpl<Void>
	) {
		completeAttribution.observe { [weak self] attribution in
			guard let self else { return }

			switch attribution {
			case .failure(let error):
				self.logger.error("Failed to publish custom user id", fields.with("exception", error))
				_ = result.reject(error)

			case .success(let response):
				if let existingRequest = RunningCustomUserIdRequests.offer(
					installId: response.installId,
					customUserId: customUserId,
					future: result.toFuture()
				) {
					existingRequest.observe { existingRequestResult in
						_ = result.fulfill(existingRequestResult)
					}
					return
				}

				// ensure we didn't already finish publishing the user id at this point
				if CustomUserIdStore.getPendingId() == nil {
					_ = result.resolve(Void())
					return
				}

				self.logger.info("Publishing new custom user id", fields)
				let body = DTOPublishCustomUserIdRequest(installId: self.installId.value, customUserId: customUserId)
				self.httpClient.sendCustomUserId(
					request: body,
					userData: UserData(
						idfa: adIds.idfa,
						userId: adIds.userId,
						installId: self.installId
					)
				).observe { customUserIdResponse in
					switch customUserIdResponse {
					case .failure(let error):
						self.logger.error("Failed to publish custom user id", fields.with("exception", error))
						_ = result.reject(error)
					case .success:
						CustomUserIdStore.setStoredAtBackend(installId: self.installId, customUserId: customUserId)
						_ = result.resolve(Void())
					}
				}
			}
		}
	}

	private func forward(adImpression: AdImpression, extraDimensions: [String: String]) -> Future<Void> {
		let result = FutureImpl<Void>()

		if let revenue = adImpression.revenue, revenue.value < 0 {
			logger.warn(
				"Negative revenue for AdFormat",
				LoggerFieldsImpl()
					.with("adUnit", adImpression.unit)
					.with("revenue", revenue.value)
					.with("currency", revenue.currency)
			)

			return result.reject(JustTrackError.custom("Negative revenue for AdFormat"))
		}

		var event: AppEvent = JtAdInternalEvent(
			jtAction: "success",
			jtAdBundleId: adImpression.bundleId,
			jtAdInstanceName: adImpression.instanceName,
			jtAdNetwork: adImpression.network,
			jtAdPlacement: adImpression.placement,
			jtAdSdk: adImpression.sdkName,
			jtAdSegment: adImpression.segmentName,
			jtAdUnit: adImpression.unit,
			jtAdTestGroup: adImpression.testGroup,
			revenue: adImpression.revenue,
			happenedAt: Date()
		)

		for (k, v) in extraDimensions {
			event = event.add(dimension: k, value: v)
		}

		do {
			try event.validate()
		} catch {
			logger.warn(
				"Not publishing invalid ad impression: \(error)",
				LoggerFieldsImpl()
					.with("adUnit", adImpression.unit)
					.with("revenue", adImpression.revenue?.value ?? 0.0)
					.with("currency", adImpression.revenue?.currency ?? "USD")
			)

			return result.reject(JustTrackError.custom("Invalid ad impression"))
		}

		return track(event: event)
	}

	private func readReceiptData() -> String? {
		if let appStoreReceiptUrl = Bundle.main.appStoreReceiptURL, FileManager.default.fileExists(atPath: appStoreReceiptUrl.path) {
			do {
				let receiptData = try Data(contentsOf: appStoreReceiptUrl, options: .alwaysMapped)

				return receiptData.base64EncodedString()
			} catch {
				logger.error("Failed to read receipt data", LoggerFieldsImpl().with("error", error))
			}
		} else {
			logger.debug("No receipt data file available")
		}

		return nil
	}

	private func proceedWithTrackingAuthorizationRequest() {
		let idfa = adTrackingProvider.provideIDFA()
		let deviceInfo = DeviceInfo(idfvProvider: adTrackingProvider)
		let uniqueId = getUniqueId(advertiserId: idfa?.value ?? "", trackingId: trackingId ?? "", deviceId: deviceInfo.idfv?.value ?? "")
		let userId = store.getUserId(bundleId: bundleId, uniqueId: uniqueId)

		if needsToGetIdfa {
			needsToGetIdfa = false
			_ = getAdIdsResult.resolve(AdIds(idfa: idfa, userId: userId))

		} else if let attributionOutput, let idfa {
			if attributionOutput.isFulfilled {
				performAttributionAfterGettingIdfa(idfa: idfa, userId: userId)
			} else {
				attributionOutput.observe { [weak self] _ in
					self?.performAttributionAfterGettingIdfa(idfa: idfa, userId: userId)
				}
			}
		}
	}

	private func performAttributionAfterGettingIdfa(idfa: StringID?, userId: StringID) {
		let newGetAdIdsResult = FutureImpl<AdIds>(AdIds(idfa: idfa, userId: userId))
		self.getAdIdsResult = newGetAdIdsResult
		_ = self.getAttributionOutput(forcedDecision: .fetchAttributionAfterGettingIdfa)
	}

	func onFinishAdTrackingAuthorization() {
		proceedWithTrackingAuthorizationRequest()
	}

	func onPublishAdTrackingEvent(_ event: AppEvent) {
		_ = track(event: event)
	}
}
