import Foundation

/// Represents an ad impression to be sent to the justtrack backend. This class is used to collect
/// data related to ad impressions, which can be utilized to calculate the ad revenue generated by
/// your app.
public class AdImpression {
	let unit: String
	let sdkName: String
	var network: String?
	var placement: String?
	var testGroup: String?
	var segmentName: String?
	var instanceName: String?
	var bundleId: String?
	var revenue: Money?

	/// Initializes a new AdImpression with unit and SDK name.
	/// - Parameters:
	///   - unit: The ad unit identifier.
	///   - sdkName: The name of the ad SDK.
	public init(unit: String, sdkName: String) {
		self.unit = unit
		self.sdkName = sdkName
		self.network = nil
		self.placement = nil
		self.testGroup = nil
		self.segmentName = nil
		self.instanceName = nil
		self.bundleId = nil
		self.revenue = nil
	}

	/// Convenience initializer using AdUnit enum.
	/// - Parameters:
	///   - unit: The ad unit.
	///   - sdkName: The name of the ad SDK.
	public convenience init(unit: AdUnit, sdkName: String) {
		self.init(unit: unit.name, sdkName: sdkName)
	}

	/// Sets the network for this ad impression.
	///
	/// - Parameter network: The name of the ad network which provided the ad. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(network: String?) -> Self {
		self.network = network

		return self
	}

	/// Sets the placement for this ad impression.
	///
	/// - Parameter placement: The placement of the ad. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(placement: String?) -> Self {
		self.placement = placement

		return self
	}

	/// Sets the test group for this ad impression.
	///
	/// - Parameter testGroup: The test group of the user if we are A/B testing. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(testGroup: String?) -> Self {
		self.testGroup = testGroup

		return self
	}

	/// Sets the segment name for this ad impression.
	///
	/// - Parameter segmentName: The name of the segment of the ad. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(segmentName: String?) -> Self {
		self.segmentName = segmentName

		return self
	}

	/// Sets the instance name for this ad impression.
	///
	/// - Parameter instanceName: The name of the instance of the ad. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(instanceName: String?) -> Self {
		self.instanceName = instanceName

		return self
	}

	/// Sets the bundle ID for this ad impression.
	///
	/// - Parameter bundleId: The bundle ID of the advertised app. May be nil.
	/// - Returns: This instance to allow for method chaining.
	public func set(bundleId: String?) -> Self {
		self.bundleId = bundleId

		return self
	}

	/// Sets the revenue for this ad impression.
	///
	/// - Parameter revenue: The amount of revenue this ad generated. May be zero but must not be negative.
	/// - Returns: This instance to allow for method chaining.
	public func set(revenue: Money?) -> Self {
		self.revenue = revenue

		return self
	}
}
