/// An enum describing all possible dimensions of a UserEvent.
public enum Dimension: String {
	case jtAction = "jt_action"
	case jtAdBundleId = "jt_ad_bundle_id"
	case jtAdInstanceName = "jt_ad_instance_name"
	case jtAdNetwork = "jt_ad_network"
	case jtAdPlacement = "jt_ad_placement"
	case jtAdSdk = "jt_ad_sdk"
	case jtAdSegment = "jt_ad_segment"
	case jtAdTestGroup = "jt_ad_test_group"
	case jtAdUnit = "jt_ad_unit"
	case jtCategory = "jt_category"
	case jtConnectionType = "jt_connection_type"
	case jtContext = "jt_context"
	case jtDetail = "jt_detail"
	case jtGlobal0 = "jt_global_0"
	case jtGlobal1 = "jt_global_1"
	case jtGlobal2 = "jt_global_2"
	case jtItemId = "jt_item_id"
	case jtItemName = "jt_item_name"
	case jtItemType = "jt_item_type"
	case jtLocation = "jt_location"
	case jtMethod = "jt_method"
	case jtProductId = "jt_product_id"
	case jtProductType = "jt_product_type"
	case jtProgression1 = "jt_progression_1"
	case jtProgression2 = "jt_progression_2"
	case jtProgression3 = "jt_progression_3"
	case jtState = "jt_state"
	case jtToken = "jt_token"
	case jtTrigger = "jt_trigger"
	case jtUrl = "jt_url"
}
